In [6]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

In [7]:
random_state = 0 
data = pd.read_csv('./scenarii.csv', encoding="ISO-8859-1", sep=";", header = 0)
data.head()

texte      tag
0  4.\tVersion Desktop - liste des cas d'utilisat...    texte
1                4.1.1\tCU001-001 Afficher le header  usecase
2                                Acteur : Internaute   acteur
3  Cas d’utilisation permettant à un internaute  ...    texte
4  •\tNotes :\nLe système affiche les éléments su...    texte

In [8]:
data

texte      tag
0     4.\tVersion Desktop - liste des cas d'utilisat...    texte
1                   4.1.1\tCU001-001 Afficher le header  usecase
2                                   Acteur : Internaute   acteur
3     Cas d’utilisation permettant à un internaute  ...    texte
4     •\tNotes :\nLe système affiche les éléments su...    texte
5     •\tActions :\nSi l’utilisateur clique\nsur le ...   action
6         4.1.2\tCU001-002 Afficher le bouton de langue  usecase
7                                   Acteur : Internaute   acteur
8     Cas d’utilisation permettant à un internaute  ...    texte
9     •\tNotes :\nLe système affiche :\nla langue sé...    texte
10    •\tActions :\nAu clic sur la langue sélectionn...   action
11    •\tRègles de gestion :\nSi l’utilisateur cliqu...  gestion
12            4.1.3\tCU001-0021 Afficher la page Langue  usecase
13                                  Acteur : Internaute   acteur
14    Cas d’utilisation permettant à un internaute  ...    texte
15    •\tNotes :\nLe système affiche pour chaque lan...    texte
16          4.1.4\tCU001-0022 Contribuer la page langue  usecase
17               Acteur : Administrateur / Contributeur   acteur
18    Cas d’utilisation décrivant la contribution de...    texte
19    Nom du champ\t\tType de champ\tobligatoire\tCo...    texte
20            4.1.5\tCU001-003 Afficher le fil d’ariane  usecase
21                                  Acteur : Internaute   acteur
22    Cas d’utilisation permettant à un internaute  ...    texte
23    Un fil d’Ariane est présent sur toutes les pag...    texte
24    Le fil d’ariane est composé d’un lien vers la ...    texte
25    •\tRègles de gestion\nLe fil d‘ariane ne s’aff...    texte
26       4.1.6\tCU001-004 Afficher le bouton de partage  usecase
27                                  Acteur : Internaute   acteur
28    Cas d’utilisation permettant à un internaute  ...    texte
29    •\tNotes :\nLa page en cours de consultation e...    texte
...                                                 ...      ...
2352  •\tNotes : le système affiche :\nLe titre du p...    texte
2353  •\tActions :\nAu clic sur le bouton Commencer,...   action
2354  •\tRègles de gestion :\nSi une valeur de l’ent...  gestion
2355                                Acteur : Internaute   acteur
2356  Cas d’utilisation décrivant la consultation de...    texte
2357  •\tNotes :\nLa barre d’éléments s’affiche si l...    texte
2358  •\tActions :\nAu clic sur un élément du parcou...   action
2359  •\tRègles de gestion :\nL’élément en cours de ...  gestion
2360      5.10.1.e\tAfficher les éléments d’un parcours    texte
2361                                Acteur : Internaute   acteur
2362  Cas d’utilisation décrivant la consultation d’...    texte
2363  •\tNotes :\nle système affiche les information...    texte
2364  •\tActions :\nAu touch du doigt (double contac...   action
2365  •\tRègles de gestion\nPar défaut, le visuel s’...    texte
2366                  5.10.1.f\tAfficher la page de fin    texte
2367                                Acteur : Internaute   acteur
2368  Cas d’utilisation décrivant la consultation de...    texte
2369  •\tNotes :\nLe système affiche les éléments su...    texte
2370  •\tActions :\nAu clic sur le bouton Recommence...   action
2371  •\tRègles de gestion\nSi aucune valeur n’est s...    texte
2372  5.10.2\tAfficher tous les parcours\n5.10.2.a\t...    texte
2373                                Acteur : Internaute   acteur
2374  Cas d’utilisation décrivant la consultation du...    texte
2375  •\tNotes :\nLe système affiche 2 menus déroula...    texte
2376  •\tActions :\nA la sélection d’une valeur dans...   action
2377  •\tRègles de gestion :\nA la sélection d’une v...  gestion
2378           5.10.2.b\tAfficher la liste des parcours    texte
2379                                Acteur : Internaute   acteur
2380  Cas d’utilisation décrivant la consultation de...    texte
2381  •\tNotes :\nLe système affiche la liste des pa...    texte

[2382 rows x 2 colu

## extraction des caractéristiques 

In [9]:
vec = TfidfVectorizer(max_features=1000, stop_words=stopwords.words('french'))
vec.fit(data['texte'].values)
features = vec.transform(data['texte'].values)

In [10]:
#Nous obtenons une matrice carractérisée par 1000 mots
features

<2382x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 29551 stored elements in Compressed Sparse Row format>

In [11]:
features.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.53024634, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## Construction du Modèle KNN

In [12]:
#La Métrique cosine est généralement utilisé pour la similitude de texte
knn = NearestNeighbors(n_neighbors=10, metric='cosine')
knn.fit(features)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)

In [13]:
#Observation des 10 voisins les plus proches au 1er texte ainsi que les distances qui les séparent
knn.kneighbors(features[0:1], return_distance=True)

(array([[0.        , 0.25255254, 0.46387054, 0.52207988, 0.62989629,
         0.6873987 , 0.71118778, 0.71118778, 0.71655571, 0.72768479]]),
 array([[   0, 1706, 1598, 1597,  454,  174,  379, 1791,   59, 1626]],
       dtype=int64))

## A partir d'un user story pris dans une matrice de couverture, récupérons ses 10 voisins les plus proches et comparons

In [14]:
input_texts = ["L’utilisateur peut créer un lien de niveau 1"]
input_features = vec.transform(input_texts)

D, N = knn.kneighbors(input_features, n_neighbors=10, return_distance=True)

for input_text, distances, neighbors in zip(input_texts, D, N):
    print("Input text = ", input_text[:200], "\n")
    for dist, neighbor_idx in zip(distances, neighbors):
        if dist < 0.5 :
            print("Distance = ", dist, "Neighbor idx = ", neighbor_idx)
            print(data['texte'].values[neighbor_idx][:200])
            print("-"*200)
    print("="*200)
    print()

Input text =  L’utilisateur peut créer un lien de niveau 1 

Distance =  0.15245928033846678 Neighbor idx =  69
•	Notes :
L’utilisateur peut créer un lien de niveau 1
L’utilisateur peut créer un lien de niveau 2
Le contributeur peut ajouter toute page dans le footer front-office
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Distance =  0.2814280431405116 Neighbor idx =  40
•	Notes :
L’utilisateur peut créer un lien de niveau 1
L’utilisateur peut créer un lien de niveau 2
Une page nouvellement créée en back-office est visible automatiquement dans le menu front-office
2 b
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



In [15]:
input_texts = ["Le contributeur se place dans une page éditoriale et ajoute un plugin bloc Image. Il peut :Sélectionner une image existante [...]"]
input_features = vec.transform(input_texts)

D, N = knn.kneighbors(input_features, n_neighbors=10, return_distance=True)

for input_text, distances, neighbors in zip(input_texts, D, N):
    print("Input text = ", input_text[:200], "\n")
    for dist, neighbor_idx in zip(distances, neighbors):
        if dist < 0.5 :
            print("Distance = ", dist, "Neighbor idx = ", neighbor_idx)
            print(data['texte'].values[neighbor_idx][:200])
            print("-"*200)
    print("="*200)
    print()

Input text =  Le contributeur se place dans une page éditoriale et ajoute un plugin bloc Image. Il peut :Sélectionner une image existante [...] 

Distance =  0.26729559364136923 Neighbor idx =  303
Cas d’utilisation décrivant la contribution d’un contenu éditorial Image.
Le contributeur se place dans une page éditoriale et ajoute un plugin bloc Image. Il peut :
•	Sélectionner une image existante
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Distance =  0.42651248223543203 Neighbor idx =  298
Cas d’utilisation décrivant la contribution d’un bloc éditorial dans une page éditoriale.
Le contributeur se place dans une page éditoriale et ajoute un bloc Texte et image.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Nous remarquons plus ou moins une similarité entre le user story et ses 10 voisins autour du mot 'utilisateur' et les verbes d'actions utilisés