In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from nltk.corpus import stopwords
import warnings
warnings.filterwarnings('ignore')

In [2]:
data1 = pd.read_excel (r'./Matric_Couverture3_evolution.xlsx', index_col=None, header=None)
data1

0     \
0                                           Evolution:   
1                                                  NaN   
2                  4.1.1\tCU001-001 Afficher le header   
3        4.1.2\tCU001-002 Afficher le bouton de langue   
4            4.1.3\tCU001-0021 Afficher la page Langue   
5          4.1.4\tCU001-0022 Contribuer la page langue   
6            4.1.5\tCU001-003 Afficher le fil d’ariane   
7       4.1.6\tCU001-004 Afficher le bouton de partage   
8      4.1.7\tCU001-005 Afficher le menu de navigation   
9      4.1.8\tCU001-006 Modifier le menu de navigation   
10   4.1.9\tCU001-007 Afficher du contenu dans une ...   
11   4.1.10\tCU001-008 Contribuer du contenu dans u...   
12          4.1.11\tCU001-009 Afficher la télécommande   
13          4.1.12\tCU001-010 Modifier la télécommande   
14                4.1.13\tCU001-011 Afficher le footer   
15                4.1.14\tCU001-012 Modifier le footer   
16   4.1.15\tCU001-013 Afficher le bloc de contenu ...   
17   4.1.16\tCU001-014 Modifier le bloc de contenu ...   
18      4.1.17\tCU001-015 Contribuer un type de public   
19   4.1.18\tCU001-016 Contribuer un type de billet...   
20   4.2.1.a\tCU002-001 Afficher les éléments de la...   
21   4.2.1.b\tCU002-002 Afficher la barre d’informa...   
22     4.2.1.c\tCU002-003 Afficher le bloc Identitaire   
23       4.2.1.d\tCU002-004 Afficher le bloc Carrousel   
24   4.2.1.e\tCU002-005 Afficher le bloc Plan d’acc...   
25   4.2.1.f\tCU002-006 Afficher la liste des parco...   
26       4.2.1.g\tCU002-007 Afficher le bloc Vous êtes   
27   4.2.2.a\tCU002-008 Contribuer la barre d’infor...   
28   4.2.2.b\tCU002-009 Contribuer le bloc Identitaire   
29   4.2.2.c\tCU002-010 Contribuer une vidéo du blo...   
..                                                 ...   
254  5.4.3.d\tCU104-007 Afficher les résultats Prog...   
255  5.4.3.e\tCU104-008 Afficher les résultats Obje...   
256  5.4.3.f\tCU104-009 Afficher les résultats Docu...   
257   5.4.3.g\tCU104-010 Afficher les résultats Medias   
258  5.4.3.h\tCU104-011 Afficher le détail d’un élé...   
259  5.5.1.a\tCU005-000 Afficher les éléments de pl...   
260  5.5.6.c\tCU105-0335 Afficher un panier de noti...   
261  5.5.6.d\tCU105-0336 Afficher un élément du pan...   
262  5.8.1\tCU009-001 Afficher les onglets médias d...   
263              5.8.2.a\tCU009-003 Afficher le filtre   
264    5.8.2.b\tCU009-005 Afficher la liste des vidéos   
265  5.8.2.c\tCU009-006 Afficher le média vidéo pri...   
266              5.8.3.a\tCU009-101 Afficher le filtre   
267  5.8.3.b\tCU009-103 Afficher la liste des docum...   
268  5.8.3.c\tCU009-104 Afficher le document audio ...   
269              5.8.4.a\tCU009-201 Afficher le filtre   
270  5.8.4.b\tCU009-202 Afficher la liste des appli...   
271  5.8.4.c\tCU009-203 Afficher l’application prin...   
272              5.8.5.a\tCU009-301 Afficher le filtre   
273  5.8.5.b\tCU009-302 Afficher la liste des docum...   
274  5.8.5.c\tCU009-303 Afficher le document 3D pri...   
275      5.8.7.a\tCU009-402 Afficher les accès rapides   
276            5.8.7.b\tCU009-403 Afficher les filtres   
277  5.8.7.c\tCU009-404 Afficher la liste des éléme...   
278  5.8.7.d\tCU009-4025 Afficher le document dans ...   
279              5.8.8.a\tCU009-502 Afficher le filtre   
280  5.8.8.b\tCU009-503 Afficher la liste de docume...   
281  5.8.8.c\tCU009-504 Afficher le document Access...   
282  5.8.9.b\tCU009-603 Afficher la liste de docume...   
283  5.8.9.c\tCU009-604 Afficher le document Appren...   

                                                  1     \
0                                                    0   
1    le système affiche les boutons des réseaux soc...   
2                                                    X   
3                                                  NaN   
4                                                  NaN   
5                                                  NaN   
6                                              

In [3]:
data = pd.DataFrame(data1)
data

0     \
0                                           Evolution:   
1                                                  NaN   
2                  4.1.1\tCU001-001 Afficher le header   
3        4.1.2\tCU001-002 Afficher le bouton de langue   
4            4.1.3\tCU001-0021 Afficher la page Langue   
5          4.1.4\tCU001-0022 Contribuer la page langue   
6            4.1.5\tCU001-003 Afficher le fil d’ariane   
7       4.1.6\tCU001-004 Afficher le bouton de partage   
8      4.1.7\tCU001-005 Afficher le menu de navigation   
9      4.1.8\tCU001-006 Modifier le menu de navigation   
10   4.1.9\tCU001-007 Afficher du contenu dans une ...   
11   4.1.10\tCU001-008 Contribuer du contenu dans u...   
12          4.1.11\tCU001-009 Afficher la télécommande   
13          4.1.12\tCU001-010 Modifier la télécommande   
14                4.1.13\tCU001-011 Afficher le footer   
15                4.1.14\tCU001-012 Modifier le footer   
16   4.1.15\tCU001-013 Afficher le bloc de contenu ...   
17   4.1.16\tCU001-014 Modifier le bloc de contenu ...   
18      4.1.17\tCU001-015 Contribuer un type de public   
19   4.1.18\tCU001-016 Contribuer un type de billet...   
20   4.2.1.a\tCU002-001 Afficher les éléments de la...   
21   4.2.1.b\tCU002-002 Afficher la barre d’informa...   
22     4.2.1.c\tCU002-003 Afficher le bloc Identitaire   
23       4.2.1.d\tCU002-004 Afficher le bloc Carrousel   
24   4.2.1.e\tCU002-005 Afficher le bloc Plan d’acc...   
25   4.2.1.f\tCU002-006 Afficher la liste des parco...   
26       4.2.1.g\tCU002-007 Afficher le bloc Vous êtes   
27   4.2.2.a\tCU002-008 Contribuer la barre d’infor...   
28   4.2.2.b\tCU002-009 Contribuer le bloc Identitaire   
29   4.2.2.c\tCU002-010 Contribuer une vidéo du blo...   
..                                                 ...   
254  5.4.3.d\tCU104-007 Afficher les résultats Prog...   
255  5.4.3.e\tCU104-008 Afficher les résultats Obje...   
256  5.4.3.f\tCU104-009 Afficher les résultats Docu...   
257   5.4.3.g\tCU104-010 Afficher les résultats Medias   
258  5.4.3.h\tCU104-011 Afficher le détail d’un élé...   
259  5.5.1.a\tCU005-000 Afficher les éléments de pl...   
260  5.5.6.c\tCU105-0335 Afficher un panier de noti...   
261  5.5.6.d\tCU105-0336 Afficher un élément du pan...   
262  5.8.1\tCU009-001 Afficher les onglets médias d...   
263              5.8.2.a\tCU009-003 Afficher le filtre   
264    5.8.2.b\tCU009-005 Afficher la liste des vidéos   
265  5.8.2.c\tCU009-006 Afficher le média vidéo pri...   
266              5.8.3.a\tCU009-101 Afficher le filtre   
267  5.8.3.b\tCU009-103 Afficher la liste des docum...   
268  5.8.3.c\tCU009-104 Afficher le document audio ...   
269              5.8.4.a\tCU009-201 Afficher le filtre   
270  5.8.4.b\tCU009-202 Afficher la liste des appli...   
271  5.8.4.c\tCU009-203 Afficher l’application prin...   
272              5.8.5.a\tCU009-301 Afficher le filtre   
273  5.8.5.b\tCU009-302 Afficher la liste des docum...   
274  5.8.5.c\tCU009-303 Afficher le document 3D pri...   
275      5.8.7.a\tCU009-402 Afficher les accès rapides   
276            5.8.7.b\tCU009-403 Afficher les filtres   
277  5.8.7.c\tCU009-404 Afficher la liste des éléme...   
278  5.8.7.d\tCU009-4025 Afficher le document dans ...   
279              5.8.8.a\tCU009-502 Afficher le filtre   
280  5.8.8.b\tCU009-503 Afficher la liste de docume...   
281  5.8.8.c\tCU009-504 Afficher le document Access...   
282  5.8.9.b\tCU009-603 Afficher la liste de docume...   
283  5.8.9.c\tCU009-604 Afficher le document Appren...   

                                                  1     \
0                                                    0   
1    le système affiche les boutons des réseaux soc...   
2                                                    X   
3                                                  NaN   
4                                                  NaN   
5                                                  NaN   
6                                              

In [4]:
data = data.iloc[0:2]
data

0                                                  1     \
0  Evolution:                                                  0   
1         NaN  le système affiche les boutons des réseaux soc...   

                                                2     \
0                                                  0   
1  sur le logo depuis une page intérieure, le sys...   

                                                3     \
0                                                  2   
1  Sur le logo depuis la page d’accueil, le systè...   

                                                4     \
0                                                  0   
1  Si l’utilisateur clique sur le bouton d’access...   

                                                5                     6     \
0                                                  0                     3   
1  Un clic sur un bouton de réseaux sociaux perme...  Le système affiche :   

                                                7     \
0                                                  0   
1  Au clic sur la langue sélectionnée, le système...   

                                                8     \
0                                                  0   
1  Si la langue sélectionnée est français, le sys...   

                                                9     ...  \
0                                                  0  ...   
1  Si la langue sélectionnée est anglais, le syst...  ...   

                                                1148  \
0                                                  0   
1  Déplacement du doigt de gauche à droite : le s...   

                                                1149  \
0                                                  0   
1  Déplacement du doigt de droite à gauche : le s...   

                                 1150                                 1151  \
0                                   2                                    1   
1  Au clic sur un élément du parcours  Le libellé Aller à l’œuvre suivante   

                                                1152  \
0                                                  0   
1  Au clic sur la croix, on réinitialise l’affich...   

                                                1153  \
0                                                  1   
1  Au clic sur le libellé Aller à l’œuvre suivant...   

                                                1154  \
0                                                  0   
1  Les blocs de texte sont affichés à la suite, s...   

                               1155  \
0                                 0   
1  Les ronds ne sont pas cliquables   

                                                1156  \
0                                                  1   
1  Au clic sur le visuel du parcours, le système ...   

                                                1157  
0                                                  0  
1  Libellé Champ de partage twitter    + Titre + ...  

[2 rows x 1158 columns]

In [5]:
data=data.transpose()
data = data[[1, 0]]
data.columns = ["texte", "Evolution"]
data=data.drop(index=0)
data

texte Evolution
1     le système affiche les boutons des réseaux soc...         0
2     sur le logo depuis une page intérieure, le sys...         0
3     Sur le logo depuis la page d’accueil, le systè...         2
4     Si l’utilisateur clique sur le bouton d’access...         0
5     Un clic sur un bouton de réseaux sociaux perme...         0
6                                  Le système affiche :         3
7     Au clic sur la langue sélectionnée, le système...         0
8     Si la langue sélectionnée est français, le sys...         0
9     Si la langue sélectionnée est anglais, le syst...         0
10    Si la langue sélectionnée est espagnol, le sys...         0
11    Au clic sur la deuxième ou troisième langue, l...         0
12      Si la page est traduite, celle-ci est affichée.         0
13    •\tle système redirige vers la page parente tr...         1
14    •\tSi la page parente de niveau N-1 n’est pas ...         1
15    •\tSi la page parente de niveau N-2 n’est pas ...         2
16    Le système affiche pour chaque langue ci-desso...         0
17    Le contributeur se place en mode liste sur le ...         0
18    Nom du champ\t\tType de champ\tobligatoire\tCo...         2
19    Un fil d’Ariane est présent sur toutes les pag...         0
20    Le fil d’ariane est composé d’un lien vers la ...         0
21    Au clic sur le bouton de partage, un menu supp...         0
22    Au clic sur le bouton Facebook, l’événement es...         0
23    Au clic sur le bouton Twitter, l’événement est...         0
24                                      Date / Horaires         1
25                                      Infos pratiques         1
26                                             Soutenir         0
27    le menu est affiché en haut de la fenêtre navi...         0
28            Au clic sur l’une des entrées de niveau 1         1
29    Au clic sur l’icône Etoile, l’utilisateur est ...         1
30    Les rubriques de niveau 2 s’affichent mais ne ...         0
...                                                 ...       ...
1128  Au clic sur le point d’accès du musée M*, le p...         1
1129                               Le bouton itinéraire         0
1130                              Le bouton itinéraire.         0
1131  Au clic sur le bouton Itinéraire d’un point d’...         0
1132  Au clic sur le bouton Itinéraire du musée M*, ...         1
1133  Au scroll de la page, Le système affiche un me...         0
1134  Au clic sur le bouton Retour, le système affic...         2
1135  Au scroll de la page, le système affiche un me...         1
1136  Libellé de partage de la rubrique applications...         0
1137  Par défaut, le système affiche les photos 3D d...         2
1138  Les entités catégories de la rubrique Photos p...         1
1139  Le système affiche l’entité média mise en avan...         0
1140  Le système affiche la liste les informations d...         1
1141  Au clic sur le bouton « accès rapide », le sys...         1
1142  Au clic sur le titre d’un élément, l’élément P...         2
1143      Par défaut, le système affiche l’accès rapide         1
1144  Au clic sur le titre d’un élément, celui-ci s’...         1
1145  L’utilisateur visualise ce bloc après avoir cl...         1
1146  La liste des billets. Pour chaque billet d’évé...         1
1147  Au clic sur le numéro de téléphone, le numéro ...         0
1148  Déplacement du doigt de gauche à droite : le s...         0
1149  Déplacement du doigt de droite à gauche : le s...         0
1150                 Au clic sur un élément du parcours         2
1151                Le libellé Aller à l’œuvre suivante         1
1152  Au clic sur la croix, on réinitialise l’affich...         0
1153  Au clic sur le libellé Aller à l’œuvre suivant...         1
1154  Les blocs de texte sont affichés à la suite, s...         0
1155                   Les ronds ne sont pas cliquables         0
1156  Au clic sur le visuel du parcours, le système ...         1
1157  Libellé Champ de p

## Distribution des données

In [6]:
import matplotlib.pyplot as plt 
fig = plt.figure (figsize = (8,6)) 
data.groupby ('Evolution').texte.count (). plot.bar (ylim = 0) 
plt.show ()

<Figure size 800x600 with 1 Axes>

### Découpage en données Train et test

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data["texte"], data["Evolution"].astype('int'), test_size=0.3, random_state=0)

In [8]:
# Extraction des caractéristiques en limitant le nombre de feature à 500
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

vec = TfidfVectorizer(max_features=500, lowercase=True, analyzer='word', stop_words=stopwords.words('french'),ngram_range=(1,4))
vec.fit(X_train.values)
X_train_vec = vec.transform(X_train.values)

## Naive Bayes

In [9]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_vec, y_train)

In [10]:
vec = TfidfVectorizer(max_features=500, lowercase=True, analyzer='word', stop_words=stopwords.words('french'),ngram_range=(1,4))
vec.fit(X_test.values)
X_test_vec = vec.transform(X_test.values)

In [11]:
predicted = clf.predict(X_test_vec)
np.mean(predicted == y_test)

0.45689655172413796

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predicted))

[[ 50  81   2   0]
 [ 48 105   1   0]
 [ 18  30   4   0]
 [  3   5   1   0]]


In [13]:
print(classification_report(y_test,predicted))

              precision    recall  f1-score   support

           0       0.42      0.38      0.40       133
           1       0.48      0.68      0.56       154
           2       0.50      0.08      0.13        52
           3       0.00      0.00      0.00         9

    accuracy                           0.46       348
   macro avg       0.35      0.28      0.27       348
weighted avg       0.45      0.46      0.42       348



## Naive Bayes + Sur-échatillonnage

In [14]:
from imblearn.over_sampling import RandomOverSampler
# Sur-échantillonnage
ros = RandomOverSampler()
X_ro, y_ro = ros.fit_resample(X_train_vec, y_train)

In [15]:
clf.fit(X_ro, y_ro) 

MultinomialNB()

In [16]:
y_pred = clf.predict(X_test_vec)
print(confusion_matrix(y_test,y_pred))

[[51 54 24  4]
 [50 66 37  1]
 [20 17 14  1]
 [ 2  1  5  1]]


In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.41      0.38      0.40       133
           1       0.48      0.43      0.45       154
           2       0.17      0.27      0.21        52
           3       0.14      0.11      0.12         9

    accuracy                           0.38       348
   macro avg       0.30      0.30      0.30       348
weighted avg       0.40      0.38      0.39       348



In [18]:
print(accuracy_score(y_test, y_pred))

0.3793103448275862


## Naive Bayes + Sous-échatillonnage

In [19]:
# Sous-échantillonnage
from imblearn.under_sampling import RandomUnderSampler
rUs = RandomUnderSampler()
X_ru, y_ru = rUs.fit_resample(X_train_vec, y_train)

In [20]:
clf.fit(X_ru, y_ru) 

MultinomialNB()

In [21]:
y_pred = clf.predict(X_test_vec)
print(confusion_matrix(y_test,y_pred))

[[51 30 29 23]
 [55 40 36 23]
 [10 10 11 21]
 [ 2  0  3  4]]


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.43      0.38      0.41       133
           1       0.50      0.26      0.34       154
           2       0.14      0.21      0.17        52
           3       0.06      0.44      0.10         9

    accuracy                           0.30       348
   macro avg       0.28      0.32      0.25       348
weighted avg       0.41      0.30      0.33       348



In [23]:
print(accuracy_score(y_test, y_pred))

0.3045977011494253


## Naive Bayes + Sur-échatillonnage + Sous-échatillonnage

In [24]:
# SMOTE
from imblearn.over_sampling import SMOTE
smo = SMOTE()
X_sm, y_sm = smo.fit_resample(X_train_vec, y_train)

In [25]:
clf.fit(X_sm, y_sm) 

MultinomialNB()

In [26]:
y_pred = clf.predict(X_test_vec)
print(confusion_matrix(y_test,y_pred))

[[60 52 18  3]
 [60 59 31  4]
 [22 18 12  0]
 [ 2  1  3  3]]


In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.42      0.45      0.43       133
           1       0.45      0.38      0.42       154
           2       0.19      0.23      0.21        52
           3       0.30      0.33      0.32         9

    accuracy                           0.39       348
   macro avg       0.34      0.35      0.34       348
weighted avg       0.40      0.39      0.39       348



In [28]:
print(accuracy_score(y_test, y_pred))

0.3850574712643678
